development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: suntest_development
  pool: 5
  username: root
  password: 123

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: suntest_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: suntest_production
  pool: 5
  username: root
  password: 
